site:
  about:
    siteName: 'TEKNOMADE'
    subtitle: 'Systemutvikling ♥ Markedsføring'
    siteDescription: 'Teknomader ... Gjør verden bedre med kode!'
    avatar: '/assets/media/tn-merke.png'

theme:
  social:
    facebook: 'steni'
    twitter: 'stenmorten'
    instagram: 'stenmorten'
    github: 'steni'
    other:
      - label: 'linkedin'
        link: 'https://www.linkedin.com/in/stenmorten/'
        icon: 'fa-tag'
  menu:
    #  - type: 'page'
    #    title: 'Home'
    #    url: '/'
    #  - type: "wikiSections"
 #   - type: 'taxonomy'
  #    taxonomyType: 'categories'
  #    includeTerms: true
  #    termsAtRoot: true
    - type: 'page'
      title: 'Historien'
      itemId: 'Historien'
#    - type: 'page'
#      title: 'Kurs'
#      itemId: 'Kurs'
#    - type: 'page'
#      title: 'Produkter'
#      itemId: 'Produkter'
#    - type: 'page'
#      title: 'Eventer'
#      itemId: 'Eventer'
    - type: 'page'
      title: 'CV'
      itemId: 'CV - Sten Morten Misund-Asphaug'
    - type: 'page'
      title: 'Hva sier andre?'
      itemId: 'Og hva sier de andre?'
#    - type: 'page'
#      title: 'Bli Teknomade?'
#      itemId: 'Bli en Teknomade?'
#    - type: 'page'
#      title: 'Lære?'
#      itemId: 'Lære å programmere?'
    - type: 'page'
      title: 'Kontakt'
      itemId: 'Kontakt'

    - type: 'page'
      title: 'Sbansk - Snakk med Sbanken med kode'
      itemId: 'sbanken-api-1'

  #  - type: "pages"
  #    atRoot: true
  sidebar:
    - type: recentPosts
      limit: 5
      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'

services:
  generators:
    externalIndices:
      - 'https://orchid.netlify.com/meta/all.index.json'
