permalink: ':category/:year/:monthName/:slug'
categories:
  - key: 'systemutvikling'
    title: 'Systemutvkling'
  - key: 'markedsføring'
    title: 'Markedsføring'
  - key: 'livet'
    title: 'Livet'
  - key: 'betraktninger'
    title: 'Betraktninger'
  - key: 'programming'
    title: 'Programming'
authors:
  - name: 'Sten Morten Misund-Asphaug'
    avatar: '/assets/images/smma-half-figure.jpg'
    email: 'steni@teknomade.no'
postPages:
  author: 'Sten Morten Misund-Asphaug'
  layout: single
  components:
    - type: pageContent
    - type: taxonomy
      taxonomyType: tags
    - type: taxonomy
      taxonomyType: categories
